[package]
name = "baguette-proc"
version = "0.1.0"
edition = "2021"
license.workspace = true

[dependencies]
proc-macro2 = { version = "1", features = ["nightly"] }
quote = "1"
syn = { version = "*", features = ["full"] }

[lib]
proc-macro = true